{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 682,
      "metadata": {
        "id": "J5MpfiJBKTui"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import random\n",
        "from typing import List, Dict, Tuple\n",
        "import copy\n",
        "import time\n",
        "import numpy as np\n",
        "from joblib import Parallel, delayed\n",
        "from itertools import combinations, product\n",
        "from queue import PriorityQueue, Empty\n",
        "from helpers import *"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 729,
      "metadata": {},
      "outputs": [],
      "source": [
        "nodes, costs, D = read_data(filename=\"TSPA.csv\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Representation of moves:\n",
        "1) Nodes - (node_old, node_new)\n",
        "   - node_old is the one to be exchanged in the path\n",
        "   - you can check if node is still in path\n",
        "   - you can check if node_value_new is already used in path\n",
        "   - when you create new path just brute force enumerate, it is still fast\n",
        "2) Edges - ((edge1_start, edge1_end), (edge2_start, edge2_end))\n",
        "   - 4 node indeces\n",
        "   - you can easily check if edge still exists in path\n",
        "   - you can check the opposite order easily"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 730,
      "metadata": {
        "id": "NtIVjLP9DGFM"
      },
      "outputs": [],
      "source": [
        "class Move:\n",
        "    def __init__(self, delta_value: int, move_type: str, values: tuple, adjacent=None):\n",
        "        self.delta = delta_value\n",
        "        self.type = move_type\n",
        "        self.values = values\n",
        "        self.adjacent = adjacent\n",
        "        self.reversed = False\n",
        "    def __gt__(self, _):\n",
        "        return True\n",
        "    def __lt__(self, _):\n",
        "        return False\n",
        "    def create_path(self, path):\n",
        "        if self.type == 'nodes':\n",
        "            new_path = path[:]\n",
        "            old_node, new_node = self.values\n",
        "            old_node_idx = new_path.index(old_node)\n",
        "            new_path[old_node_idx] = new_node\n",
        "            return new_path\n",
        "        elif self.type == 'edges':\n",
        "            edge1, edge2 = self.values\n",
        "            if self.reversed:\n",
        "                n1 = path.index(edge1[1])\n",
        "                n2 = path.index(edge2[1])\n",
        "            else:\n",
        "                n1 = path.index(edge1[0])\n",
        "                n2 = path.index(edge2[0])\n",
        "            if n1 < n2:\n",
        "                return path[:n1] + [path[n1]] + [path[n2]] + path[n1+1:n2][::-1] + path[n2+1:]\n",
        "            else:\n",
        "                return path[n2+1:n1] + [path[n1]] + [path[n2]] + path[:n2][::-1] + path[n1+1:][::-1]\n",
        "        else:\n",
        "            raise ValueError(\"Invalid delta_type!\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 754,
      "metadata": {},
      "outputs": [],
      "source": [
        "def print_move(move, prefix='Putting'):\n",
        "    print(f'{prefix} {move.type} move {move.values} with delta: {move.delta}')\n",
        "\n",
        "def get_nodes_delta(old_node, new_node, path, D, costs, prev, next):\n",
        "    old_dist = D[prev, old_node] + D[old_node, next]\n",
        "    new_dist = D[prev, new_node] + D[new_node, next]\n",
        "    delta = new_dist - old_dist + costs[new_node] - costs[old_node]\n",
        "    return int(delta)\n",
        "\n",
        "def get_edges_delta(edge1, edge2, D):\n",
        "    return int(( D[edge1[0], edge2[0]] + D[edge1[1], edge2[1]] ) \\\n",
        "          - ( D[edge1[0], edge1[1]] + D[edge2[1], edge2[0]] ))\n",
        "\n",
        "def nodes_inter(path, D, costs):\n",
        "    og_nodes = set(path)\n",
        "    nodes = set(list(range(D.shape[0])))\n",
        "    changes = product(og_nodes, nodes - og_nodes)\n",
        "    moves = []\n",
        "    for change in changes:\n",
        "        old_node, new_node = change\n",
        "        index_of_old_node = path.index(old_node)\n",
        "        prev = int(path[(index_of_old_node - 1) % len(path)])\n",
        "        next = int(path[(index_of_old_node + 1) % len(path)])\n",
        "        delta = get_nodes_delta(old_node, new_node, path, D, costs, prev, next)\n",
        "        move = Move(delta, 'nodes', (old_node, new_node), adjacent=(prev, next))\n",
        "        moves.append(move)\n",
        "    return moves\n",
        "\n",
        "def edges_intra(path, distance_matrix):\n",
        "    pairs1 = np.column_stack((path[:-1], path[1:]))\n",
        "    cyclic_pair = np.array([path[-1], path[0]])\n",
        "    all_edges = np.vstack((pairs1, cyclic_pair))\n",
        "    edge_swaps = combinations(all_edges, 2)\n",
        "    moves = []\n",
        "    for swap in edge_swaps:\n",
        "        edge1, edge2 = [tuple(arr) for arr in swap]\n",
        "        if edge1[1] == edge2[0] or edge1[0] == edge2[1]:\n",
        "            continue\n",
        "        delta1 = get_edges_delta(edge1, edge2, distance_matrix)\n",
        "        delta2 = get_edges_delta(edge1, edge2[::-1], distance_matrix)\n",
        "        move1 = Move(delta1, 'edges', (edge1, edge2))\n",
        "        move2 = Move(delta2, 'edges', (edge1, edge2[::-1]))\n",
        "        moves.extend([move1, move2])\n",
        "    return moves\n",
        "\n",
        "def get_initial_moves(current_path, distance_matrix, costs):\n",
        "        moves_inter = nodes_inter(current_path, distance_matrix, costs)\n",
        "        moves_intra = edges_intra(current_path, distance_matrix)\n",
        "        return moves_inter + moves_intra\n",
        "\n",
        "# Scenario 1 - edges are in solution in order or both in reversed order - Apply - correct or reversed order - result of operation the same but still need to distinghuish due to create_path function in Move\n",
        "# Scenario 2 - edges are in path but one of them in the opposite order - leave but do not apply\n",
        "# Scenario 3 - edges used by the move no longer exist in path - remove\n",
        "# When checking status take into account the neighbourhood of the node when checking for nodes_exchange.\n",
        "# If one of the neighbouring nodes changes, delta for main node also changes so in future iterations\n",
        "# you need to consider that\n",
        "def get_move_status(move, path):\n",
        "    if move.type == 'nodes':\n",
        "        old_node, new_node = move.values\n",
        "        if old_node in path and new_node not in path:\n",
        "            prev_adj, next_adj = move.adjacent\n",
        "            old_node_idx = path.index(old_node)\n",
        "            prev = path[(old_node_idx-1) % len(path)]\n",
        "            next = path[(old_node_idx+1) % len(path)]\n",
        "            if prev_adj == prev and next_adj == next:\n",
        "                return \"correct order\"\n",
        "        return \"incorrect\"\n",
        "    else: # edges\n",
        "        edge1, edge2 = move.values\n",
        "        edge1_start, edge1_end = edge1\n",
        "        edge2_start, edge2_end = edge2\n",
        "        tmp_path = path + [path[0]]\n",
        "        # check if both edge1 and edge2 are in path in order\n",
        "        # and if either edge1 or edge2 are in path in opposite order\n",
        "        e1_order, e2_order = False, False\n",
        "        e1_opposite, e2_opposite = False, False\n",
        "        for idx, node_val in enumerate(tmp_path):\n",
        "            if idx == len(tmp_path)-1:\n",
        "                break\n",
        "            if edge1_start == node_val and edge1_end == tmp_path[idx+1]:\n",
        "                e1_order = True\n",
        "            if edge2_start == node_val and edge2_end == tmp_path[idx+1]:\n",
        "                e2_order = True\n",
        "            if edge1_end == node_val and edge1_start == tmp_path[idx+1]:\n",
        "                e1_opposite = True\n",
        "            if edge2_end == node_val and edge2_start == tmp_path[idx+1]:\n",
        "                e2_opposite = True\n",
        "        if e1_order and e2_order:\n",
        "            return \"correct order\"\n",
        "        elif e1_opposite and e2_opposite:\n",
        "            return \"reversed order\"\n",
        "        elif (e1_order and e2_opposite) or (e1_opposite and e2_order):\n",
        "            return \"partly reversed order\"\n",
        "        else:\n",
        "            return \"incorrect\"\n",
        "\n",
        "def get_best_move(moves, path):\n",
        "    moves_to_retain = [] # [(delta, move), ...]\n",
        "    choice = None\n",
        "    while not moves.empty():\n",
        "        delta, move = moves.get()\n",
        "        status = get_move_status(move, path)\n",
        "        if status == \"correct order\":\n",
        "            move.reversed = False\n",
        "            choice = move\n",
        "            break\n",
        "        elif status == \"reversed order\":\n",
        "            move.reversed = True\n",
        "            choice = move\n",
        "            break\n",
        "        elif status == \"partly reversed order\":\n",
        "            moves_to_retain.append((delta, move))\n",
        "            # you can't put the move back in here because of infinite loop\n",
        "        else:\n",
        "            continue\n",
        "    for delta_move in moves_to_retain:\n",
        "        moves.put(delta_move)\n",
        "    return choice\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 755,
      "metadata": {},
      "outputs": [],
      "source": [
        "def update_moves(moves: PriorityQueue, last_move, path, costs, D) -> PriorityQueue:\n",
        "    if moves.empty():\n",
        "        new_moves = get_initial_moves(path, D, costs)\n",
        "        for move in new_moves:\n",
        "            if move.delta < 0:\n",
        "                moves.put((move.delta, move))\n",
        "        return moves\n",
        "    else:\n",
        "        new_path = last_move.create_path(path)\n",
        "        new_path.append(new_path[0])\n",
        "        nodes_not_in_path = [x for x in range(len(D)) if x not in new_path]\n",
        "\n",
        "        if last_move.type == 'nodes':\n",
        "            old_node, new_node = last_move.values\n",
        "            old_node_idx = path.index(old_node)\n",
        "            prev = int(new_path[(old_node_idx - 1) % len(new_path)])\n",
        "            next = int(new_path[(old_node_idx + 1) % len(new_path)])\n",
        "            # moves for exchanging newly added node\n",
        "            for node in nodes_not_in_path:\n",
        "                exchange = (new_node, node)\n",
        "                delta = get_nodes_delta(new_node, node, new_path, D, costs, prev, next)\n",
        "                if delta < 0:\n",
        "                    move = Move(delta, 'nodes', exchange, adjacent=(prev, next))\n",
        "                    moves.put((delta, move))\n",
        "            # when exchanging node you change only edges\n",
        "            # moves for exchanging newly added edges\n",
        "            new_edge1 = (prev, new_node)\n",
        "            new_edge2 = (new_node , next)\n",
        "            usable_edges = []\n",
        "            # get all edges except for newly added ones\n",
        "            for idx, node in enumerate(new_path):\n",
        "                if idx == len(new_path)-1:\n",
        "                    break\n",
        "                next_node = new_path[idx+1]\n",
        "                if node == new_node or next_node == new_node: # new edges\n",
        "                    continue\n",
        "                usable_edges.append((node, next_node))\n",
        "            # for each usable edge in path, make a possible exchange\n",
        "            # with each one of two newly introduced edges\n",
        "            for tmp_edge in [new_edge1, new_edge2]:\n",
        "                for edge in usable_edges:\n",
        "                    exchanges = [\n",
        "                        (tmp_edge, edge),\n",
        "                        (tmp_edge, edge[::-1]),\n",
        "                    ]\n",
        "                    for edge1, edge2 in exchanges:\n",
        "                        delta = get_edges_delta(edge1, edge2, D)\n",
        "                        if delta < 0:\n",
        "                            move = Move(delta, 'edges', (edge1, edge2))\n",
        "                            moves.put((delta, move))\n",
        "        else:\n",
        "            # Add moves for new edges, to every other edge\n",
        "            edge1, edge2 = last_move.values\n",
        "            edge1_start, edge1_end = edge1\n",
        "            edge2_start, edge2_end = edge2\n",
        "            new_edge1 = (edge1_start, edge2_start)\n",
        "            new_edge2 = (edge1_end, edge2_end)\n",
        "            # when exchanging 2 edges, the neighbourhood of 4 nodes changes,\n",
        "            # so you need to add nodes exchanges for each of them\n",
        "            for changed_node in (edge1_start, edge2_start, edge1_end, edge2_end):\n",
        "                node_idx = new_path.index(changed_node)\n",
        "                prev = int(new_path[(node_idx - 1) % len(path)])\n",
        "                next = int(new_path[(node_idx + 1) % len(path)])\n",
        "                for node in nodes_not_in_path:\n",
        "                    exchange = (changed_node, node)\n",
        "                    delta = get_nodes_delta(changed_node, node, new_path, D, costs, prev, next)\n",
        "                    if delta < 0:\n",
        "                        move = Move(delta, 'nodes', exchange, adjacent=(prev, next))\n",
        "                        moves.put((delta, move))\n",
        "\n",
        "            usable_edges = []\n",
        "            # get all edges except for newly added ones\n",
        "            for idx, node in enumerate(new_path):\n",
        "                if idx == len(new_path)-1:\n",
        "                    break\n",
        "                next_node = new_path[idx+1]\n",
        "                # currently on edge - (node, next_node)\n",
        "                if (node == new_edge1[0] and next_node == new_edge1[1]) or \\\n",
        "                   (node == new_edge2[0] and next_node == new_edge2[1]):\n",
        "                    continue\n",
        "                usable_edges.append((node, next_node))\n",
        "\n",
        "            for tmp_edge in [new_edge1, new_edge2]:\n",
        "                for edge in usable_edges:\n",
        "                    exchanges = [\n",
        "                        (tmp_edge, edge),\n",
        "                        (tmp_edge, edge[::-1]),\n",
        "                    ]\n",
        "                    for edge1, edge2 in exchanges:\n",
        "                        delta = get_edges_delta(edge1, edge2, D)\n",
        "                        if delta < 0:\n",
        "                            move = Move(delta, 'edges', (edge1, edge2))\n",
        "                            moves.put((delta, move))\n",
        "        return moves"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 759,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "78582\n"
          ]
        }
      ],
      "source": [
        "def local_search_deltas(current_path, costs, D):\n",
        "    moves = PriorityQueue()\n",
        "    moves = update_moves(moves, None, current_path, costs, D)\n",
        "    while True:\n",
        "        best_move = get_best_move(moves, current_path)\n",
        "        if best_move is None:\n",
        "            break\n",
        "        else:\n",
        "            moves = update_moves(moves, best_move, current_path, costs, D)\n",
        "            current_path = best_move.create_path(current_path)\n",
        "\n",
        "    return current_path\n",
        "\n",
        "initial_solution = list(random_sequence(D))\n",
        "solution = local_search_deltas(initial_solution, costs, D)\n",
        "print(evaluate(D, solution, costs))\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "For nodes exchange you recalculate:\n",
        "1. Edge exchanges for 2 newly introduced edges\n",
        "2. Nodes exchanges for 2 surrounding nodes\n",
        "3. Nodes exchanges for newly introduced node\n",
        "\n",
        "For edges exchange you recalculate:\n",
        "1. Edge exchanges for 2 newly introduces edges\n",
        "2. Nodes exchanges for 4 nodes for which neighbourhood changed"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.10.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
